In [ ]:
import numpy as np
data = np.array([[1], [2], [3]])
data.ndim

2

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
a = np.squeeze(data)

In [ ]:
a

array([1, 2, 3])

In [ ]:
a.ndim

1

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(a, 2)
a

array([[1, 2],
       [3, 4]])

In [ ]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.roll(data, -2)

array([[3],
       [1],
       [2]])

In [ ]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [ ]:
np.diag(np.array([1, 2, 3, 4,]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.roll(a, 2, axis = 0)

array([[3, 4],
       [5, 6],
       [1, 2]])

**#binary operation on array**

In [ ]:
arr1 = np.random.randint(1, 10, (3,4))
arr2 = np.random.randint(1, 10, (3,4))


In [ ]:
arr1

array([[8, 8, 1, 8],
       [1, 1, 3, 2],
       [6, 4, 8, 9]])

In [ ]:
arr2

array([[2, 2, 4, 4],
       [1, 5, 8, 4],
       [5, 2, 4, 7]])

In [ ]:
arr1 + arr2

array([[10, 10,  5, 12],
       [ 2,  6, 11,  6],
       [11,  6, 12, 16]])

In [ ]:
arr1 * arr2

array([[16, 16,  4, 32],
       [ 1,  5, 24,  8],
       [30,  8, 32, 63]])

In [ ]:
arr1/arr2

array([[4.        , 4.        , 0.25      , 2.        ],
       [1.        , 0.2       , 0.375     , 0.5       ],
       [1.2       , 2.        , 2.        , 1.28571429]])

In [ ]:
arr1 - arr2

array([[ 6,  6, -3,  4],
       [ 0, -4, -5, -2],
       [ 1,  2,  4,  2]])

In [ ]:
arr1 ** arr2

array([[     64,      64,       1,    4096],
       [      1,       1,    6561,      16],
       [   7776,      16,    4096, 4782969]])

In [ ]:
arr1

array([[8, 8, 1, 8],
       [1, 1, 3, 2],
       [6, 4, 8, 9]])

In [ ]:
arr2

array([[2, 2, 4, 4],
       [1, 5, 8, 4],
       [5, 2, 4, 7]])

In [ ]:
arr1 > arr2

array([[ True,  True, False,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [ ]:
arr1

array([[8, 8, 1, 8],
       [1, 1, 3, 2],
       [6, 4, 8, 9]])

In [ ]:
~arr1

array([[ -9,  -9,  -2,  -9],
       [ -2,  -2,  -4,  -3],
       [ -7,  -5,  -9, -10]])

In [ ]:
arr1

array([[8, 8, 1, 8],
       [1, 1, 3, 2],
       [6, 4, 8, 9]])

#Numpy string function

In [ ]:
arr = np.array(["Abhi", "Sinha"])
arr

array(['Abhi', 'Sinha'], dtype='<U5')

In [ ]:
np.char.upper(np.array(["Abhi"]))

array(['ABHI'], dtype='<U4')

In [ ]:
np.char.capitalize(arr)

array(['Abhi', 'Sinha'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Abhi', 'Sinha'], dtype='<U5')

#Mathematical function

In [ ]:
arr1

array([[8, 8, 1, 8],
       [1, 1, 3, 2],
       [6, 4, 8, 9]])

In [ ]:
np.sin(arr1)

array([[ 0.98935825,  0.98935825,  0.84147098,  0.98935825],
       [ 0.84147098,  0.84147098,  0.14112001,  0.90929743],
       [-0.2794155 , -0.7568025 ,  0.98935825,  0.41211849]])

In [ ]:
np.cos(arr1)

array([[-0.14550003, -0.14550003,  0.54030231, -0.14550003],
       [ 0.54030231,  0.54030231, -0.9899925 , -0.41614684],
       [ 0.96017029, -0.65364362, -0.14550003, -0.91113026]])

In [ ]:
np.tan(arr1)

array([[-6.79971146, -6.79971146,  1.55740772, -6.79971146],
       [ 1.55740772,  1.55740772, -0.14254654, -2.18503986],
       [-0.29100619,  1.15782128, -6.79971146, -0.45231566]])

In [ ]:
np.log(arr1)

array([[2.07944154, 2.07944154, 0.        , 2.07944154],
       [0.        , 0.        , 1.09861229, 0.69314718],
       [1.79175947, 1.38629436, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr1)

array([[0.90308999, 0.90308999, 0.        , 0.90308999],
       [0.        , 0.        , 0.47712125, 0.30103   ],
       [0.77815125, 0.60205999, 0.90308999, 0.95424251]])

In [ ]:
np.exp(arr1)

array([[2.98095799e+03, 2.98095799e+03, 2.71828183e+00, 2.98095799e+03],
       [2.71828183e+00, 2.71828183e+00, 2.00855369e+01, 7.38905610e+00],
       [4.03428793e+02, 5.45981500e+01, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
np.power(arr1, 3)

array([[512, 512,   1, 512],
       [  1,   1,  27,   8],
       [216,  64, 512, 729]])

In [ ]:
np.mean(arr1)

4.916666666666667

In [ ]:
np.max(arr1)

9

In [ ]:
np.std(arr1)

3.0945741046045234

In [ ]:
np.max(arr1)

9

In [ ]:
arr1 - arr2

array([[ 6,  6, -3,  4],
       [ 0, -4, -5, -2],
       [ 1,  2,  4,  2]])

In [ ]:
np.subtract(arr1, arr2)

array([[ 6,  6, -3,  4],
       [ 0, -4, -5, -2],
       [ 1,  2,  4,  2]])

In [ ]:
arr1*arr2

array([[16, 16,  4, 32],
       [ 1,  5, 24,  8],
       [30,  8, 32, 63]])

In [ ]:
np.multiply(arr1, arr2)

array([[16, 16,  4, 32],
       [ 1,  5, 24,  8],
       [30,  8, 32, 63]])

In [ ]:
np.mod(arr1, arr2)

array([[0, 0, 1, 0],
       [0, 1, 3, 2],
       [1, 0, 0, 2]])

In [ ]:
np.power(arr1, arr2)

array([[     64,      64,       1,    4096],
       [      1,       1,    6561,      16],
       [   7776,      16,    4096, 4782969]])

In [ ]:
np.sqrt(arr1)

array([[2.82842712, 2.82842712, 1.        , 2.82842712],
       [1.        , 1.        , 1.73205081, 1.41421356],
       [2.44948974, 2.        , 2.82842712, 3.        ]])

#sort search

In [ ]:
arr = np.array([5, 6, 1, 2])

In [ ]:
arr

array([5, 6, 1, 2])

In [ ]:
np.sort(arr)

array([1, 2, 5, 6])

In [ ]:
arr = np.array([5, 195, 355, 53, 6654 ])

In [ ]:
arr

array([   5,  195,  355,   53, 6654])

In [ ]:
np.sort(arr)

array([   5,   53,  195,  355, 6654])

In [ ]:
np.searchsorted(arr, 3)

0

In [ ]:
np.searchsorted(arr, 53)

1

In [ ]:
arr1 = np.array([0, 1, 2, 3, 0,7,4,9])
np.count_nonzero(arr1)

6

In [ ]:
arr1>1

array([False, False,  True,  True, False,  True,  True,  True])

In [ ]:
arr1

[0, 1, 3, 0, 4]

In [ ]:
np.where(arr1 > 0)

(array([1, 2, 3, 5, 6, 7]),)

In [ ]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 7, 4, 9])

In [ ]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 504403158265495552,
       288230376151711744, 648518346341351424])

#matrix >> 2d array

In [ ]:
import numpy.matlib as nm


In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#Numpy linear algebra

In [ ]:
import numpy as np


In [ ]:
arr1 = np.random.randint(1, 10, (3, 4))

In [ ]:
arr2 = np.random.randint(1, 10, (3,4))

In [ ]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [ ]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [ ]:
a = np.array([[7, 1.5, -3], [3, -5, 2], [5, 4, -7]])

In [ ]:
a

array([[ 7. ,  1.5, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  4. , -7. ]])

In [ ]:
b = np.array([16, -8, 0])

In [ ]:
b


array([16, -8,  0])

In [ ]:
np.linalg.solve(a, b)

array([3.56626506, 6.1686747 , 6.07228916])

In [ ]:
arr1

array([[2, 3],
       [4, 5]])

In [ ]:
5*2 - 3*4

-2

In [ ]:
np.linalg.det(arr1)

-2.0

In [ ]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])