1. What is a Python library? Why do we use Python libraries?


- **ANS. **
- The Python Standard Library contains the exact syntax, semantics, and tokens of Python. It contains built-in modules that provide access to basic system functionality like I/O and some other core modules. Most of the Python Libraries are written in the C programming language. The Python standard library consists of more than 200 core modules. All these work together to make Python a high-level programming language. Python Standard Library plays a very important role. Without it, the programmers can’t have access to the functionalities of Python. But other than this, there are several other libraries in Python that make a programmer’s life easier.
1. TensorFlow: This library was developed by Google in collaboration with the Brain Team. It is an open-source library used for high-level computations. It is also used in machine learning and deep learning algorithms. It contains a large number of tensor operations. Researchers also use this Python library to solve complex computations in Mathematics and Physics.
2. Matplotlib: This library is responsible for plotting numerical data. And that’s why it is used in data analysis. It is also an open-source library and plots high-defined figures like pie charts, histograms, scatterplots, graphs, etc.
3. Pandas: Pandas are an important library for data scientists. It is an open-source machine learning library that provides flexible high-level data structures and a variety of analysis tools. It eases data analysis, data manipulation, and cleaning of data. Pandas support operations like Sorting, Re-indexing, Iteration, Concatenation, Conversion of data, Visualizations, Aggregations, etc.
4. Numpy: The name “Numpy” stands for “Numerical Python”. It is the commonly used library. It is a popular machine learning library that supports large matrices and multi-dimensional data. It consists of in-built mathematical functions for easy computations. Even libraries like TensorFlow use Numpy internally to perform several operations on tensors. Array Interface is one of the key features of this library.

5. SciPy: The name “SciPy” stands for “Scientific Python”. It is an open-source library used for high-level scientific computations. This library is built over an extension of Numpy. It works with Numpy to handle complex computations. While Numpy allows sorting and indexing of array data, the numerical data code is stored in SciPy. It is also widely used by application developers and engineers.
6. Scrapy: It is an open-source library that is used for extracting data from websites. It provides very fast web crawling and high-level screen scraping. It can also be used for data mining and automated testing of data.
7. Scikit-learn: It is a famous Python library to work with complex data. Scikit-learn is an open-source library that supports machine learning. It supports variously supervised and unsupervised algorithms like linear regression, classification, clustering, etc. This library works in association with Numpy and SciPy.

8. PyGame: This library provides an easy interface to the Standard Directmedia Library (SDL) platform-independent graphics, audio, and input libraries. It is used for developing video games using computer graphics and audio libraries along with Python programming language.

9. PyTorch: PyTorch is the largest machine learning library that optimizes tensor computations. It has rich APIs to perform tensor computations with strong GPU acceleration. It also helps to solve application issues related to neural networks.

10. PyBrain: The name “PyBrain” stands for Python Based Reinforcement Learning, Artificial Intelligence, and Neural Networks library. It is an open-source library built for beginners in the field of Machine Learning. It provides fast and easy-to-use algorithms for machine learning tasks. It is so flexible and easily understandable and that’s why is really helpful for developers that are new in research fields.


Use of Libraries in Python Program
As we write large-size programs in Python, we want to maintain the code’s modularity. For the easy maintenance of the code, we split the code into different parts and we can use that code later ever we need it. In Python, modules play that part. Instead of using the same code in different programs and making the code complex, we define mostly used functions in modules and we can just simply import them in a program wherever there is a requirement. We don’t need to write that code but still, we can use its functionality by importing its module. Multiple interrelated modules are stored in a library. And whenever we need to use a module, we import it from its library. In Python, it’s a very simple job to do due to its easy syntax. We just need to use import.

2. What is the difference between Numpy array and List?



NumPy is the fundamental package for scientific computing in Python. Numpy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences. Numpy is not another programming language but a Python extension module. It provides fast and efficient operations on arrays of homogeneous data.

Some important points about Numpy arrays:

We can create an N-dimensional array in Python using Numpy.array().
The array is by default Homogeneous, which means data inside an array must be of the same Datatype. (Note You can also create a structured array in Python).
Element-wise operation is possible.
Numpy array has various functions, methods, and variables, to ease our task of matrix computation.
Elements of an array are stored contiguously in memory. For example, all rows of a two-dimensioned array must have the same number of columns. A three-dimensional array must have the same number of rows and columns on each card.
Representation of Numpy array
Single Dimensional Numpy Array





-A Python list is a collection that is ordered and changeable. In Python, lists are written with square brackets.

Some important points about Python Lists:

The list can be homogeneous or heterogeneous.
Element-wise operation is not possible on the list.
Python list is by default 1-dimensional. But we can create an N-Dimensional list. But then too it will be 1 D list storing another 1D list
Elements of a list need not be contiguous in memory.
Below are some examples which clearly demonstrate how Numpy arrays are better than Python lists by analyzing the memory consumption, execution time comparison, and operations supported by both of them.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape
shape = array.shape

# Size
size = array.size

# Dimensions
dimensions = array.ndim

#Driver Code
print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)


Shape: (3, 4)
Size: 12
Dimensions: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Using indexing we access the 1st row of the array.
first_row = array[0]

# Using print func., Display the 1st row element
print("First row:", first_row)



First row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Access the element at the third row and fourth column
element = arr[2, 3]

print("Element at the third row and fourth column:", element)

Element at the third row and fourth column: 12


6. Write code to extract all odd-indexen elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
import numpy as np

# Define the NumPy array
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Extract all odd-indexed elements
odd_indexed_elements = arr[:, 1::2]

# Driver Code
print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?


we can generate a random 3x3 matrix with values between 0 and 1 using NumPy's random.rand function. This function creates an array of the given shape with random values sampled from a uniform distribution over the interval [0, 1].

In [ ]:
# Generate a random 3x3 matrix with values between 0 and 1
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.15544609 0.08145453 0.37297952]
 [0.89967328 0.73094069 0.04434312]
 [0.02446478 0.34983091 0.82072802]]


8. Describe the difference between np.random.rand and np.random.randn?


np.random.rand:

- `numpy.random.rand()`-  in Python is a function from the NumPy library that generates an array of specified shapes and fills it with random values uniformly distributed between 0 and 1. It is commonly used for creating random arrays in various applications such as simulations and machine learning. The function’s output is determined by the shape parameters provided.

- Randomly Constructing 1D Array
- Randomly Constructing 2D Array
- Randomly Constructing 3D Array


np.random.randn:

- The numpy.random.randn() function creates an array of specified shape and fills it with random values as per standard normal distribution.

- It also takes dimensions of the desired output array as input parameters.

- If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1




In [3]:
import numpy as np
# Generate a 2x3 array of random numbers between 0 and 1
random_array = np.random.rand(2, 3)
print(random_array)

[[0.98851409 0.74402384 0.21297141]
 [0.59792661 0.21360962 0.46833112]]


In [4]:
import numpy as np
# Generate a 2x3 array of random numbers from a standard normal distribution
random_array = np.random.randn(2, 3)
print(random_array)

[[-1.06173922 -0.34720225 -0.37455087]
 [-0.73200643  1.32684014 -1.52120737]]


9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Increase dimension using np.newaxis
new_arr = arr[:, :, np.newaxis]

# Or using np.expand_dims()
# new_arr = np.expand_dims(arr, axis=2)

print("Original array shape:", arr.shape)
print("New array shape:", new_arr.shape)
print("New array:")
print(new_arr)


Original array shape: (3, 4)
New array shape: (3, 4, 1)
New array:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]


In [ ]:
import numpy as np

# Given array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the array
transposed_arr = np.transpose(arr)
# Or transposed_arr = arr.T

print("Original array:")
print(arr)

print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplication'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om
+ Diide Matix B by A


In [ ]:
import numpy as np

# Define matrices A2 and B2
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Add both matrices
add_result = A2 + B2

# Subtract matrix B from matrix A
subtract_result = A2 - B2

# Divide matrix B by matrix A element-wise
divide_result = B2 / A2

# Drive Code
print("Addition Result:")
print(add_result)
print("\nSubtraction Result:")
print(subtract_result)
print("\nDivision Result:")
print(divide_result)


Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division Result:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?


In [ ]:
import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4], dtype=np.int32)
print("Original array:")
print(arr)

# Swap byte order
arr.byteswap(True)
print("Array with byte order swapped:")
print(arr)


Original array:
[1 2 3 4]
Array with byte order swapped:
[16777216 33554432 50331648 67108864]


- import numpy as np = This line imports the NumPy library and assigns it the alias np, allowing us to refer to NumPy functions and objects using the shorthand np.

- arr = np.array([1, 2, 3, 4], dtype=np.int32): This line creates a NumPy array named arr containing the elements [1, 2, 3, 4]. The dtype=np.int32 argument specifies that the data type of the elements in the array should be 32-bit integers.

- print("Original array:"): This line prints the string "Original array:" to the console.

- print(arr): This line prints the contents of the array arr to the console.

- arr.byteswap(True): This line swaps the byte order of the elements in the array arr. The argument True specifies that the byte order should be swapped in-place.

- print("Array with byte order swapped:"): This line prints the string "Array with byte order swapped:" to the console.

- print(arr): This line prints the contents of the array arr after the byte order has been swapped.

13. What is the significance of the np.linalg.inv function?

- Ans :--
The np.linalg.inv function in NumPy computes the inverse of a square matrix. This function is significant in various mathematical and computational contexts, including:

Solving Systems of Linear Equations: The inverse of a matrix is used to efficiently solve systems of linear equations of the form Ax = b, where A is the coefficient matrix, x is the vector of unknowns, and b is the vector of constants. Instead of solving such equations directly using methods like Gaussian elimination, you can compute the inverse of A (if it exists) and then find x = A^(-1)b.

Eigenvalue and Eigenvector Computation: In many numerical algorithms for computing eigenvalues and eigenvectors of a matrix, the inverse of the matrix or its factors may be required.

Matrix Manipulation: In various applications such as optimization, statistics, and physics, matrix inversion is a fundamental operation for tasks like least squares fitting, covariance estimation, and solving differential equations.

14. What does the np.reshape function of, and how is it used?
- Ans - Reshaping numpy array simply means changing the shape of the given array, shape basically tells the number of elements and dimension of array, by reshaping an array we can add or remove dimensions or change number of elements in each dimension.
In order to reshape a numpy array we use reshape method with the given array.
- We can also use np.reshape(array, shape) command to reshape the array
Reshaping : 1-D to 2D

- The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of an array into a new shape while preserving the total number of elements. This function does not modify the original array; instead, it returns a new array with the specified shape.

- import numpy as np

- Create a one-dimensional array
- arr = np.array([1, 2, 3, 4, 5, 6])

- Reshape the array into a 2x3 matrix

- reshaped_arr = np.reshape(arr, (2, 3))

- print(reshaped_arr)


15. What is broadcasting in Numpy?

Ans- In NumPy, broadcasting refers to the ability of arrays with different shapes to be used together in element-wise operations. When operating on arrays of different shapes, NumPy automatically broadcasts the smaller array over the larger one so that they have compatible shapes for the operation.

Here are the rules for broadcasting:

1. If the arrays do not have the same rank (number of dimensions), then the shape of the array with fewer dimensions is padded with ones on its left side.

2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

4. Broadcasting allows for efficient vectorized operations, avoiding the need for explicit looping over array elements. This makes code cleaner and more concise.